// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDla5uPuSGnyRWLA0zK0vhoCP65cMjkxA',
    appId: '1:628958599154:web:866b58c6b06f343c483d6b',
    messagingSenderId: '628958599154',
    projectId: 'attend-app-4abb4',
    authDomain: 'attend-app-4abb4.firebaseapp.com',
    storageBucket: 'attend-app-4abb4.firebasestorage.app',
    measurementId: 'G-HB1VYW8PDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6eivWKt7C38uFiGPWplwtHTcSCr9jLqE',
    appId: '1:628958599154:android:ac5b336c7e45f4fc483d6b',
    messagingSenderId: '628958599154',
    projectId: 'attend-app-4abb4',
    storageBucket: 'attend-app-4abb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNg2Jx3m1Q5bU1jcr_fcypSdh7iQRx1JY',
    appId: '1:628958599154:ios:30f9640303c0b37e483d6b',
    messagingSenderId: '628958599154',
    projectId: 'attend-app-4abb4',
    storageBucket: 'attend-app-4abb4.firebasestorage.app',
    iosBundleId: 'com.example.attendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNg2Jx3m1Q5bU1jcr_fcypSdh7iQRx1JY',
    appId: '1:628958599154:ios:30f9640303c0b37e483d6b',
    messagingSenderId: '628958599154',
    projectId: 'attend-app-4abb4',
    storageBucket: 'attend-app-4abb4.firebasestorage.app',
    iosBundleId: 'com.example.attendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDla5uPuSGnyRWLA0zK0vhoCP65cMjkxA',
    appId: '1:628958599154:web:787897a7c1433fa3483d6b',
    messagingSenderId: '628958599154',
    projectId: 'attend-app-4abb4',
    authDomain: 'attend-app-4abb4.firebaseapp.com',
    storageBucket: 'attend-app-4abb4.firebasestorage.app',
    measurementId: 'G-R36M62HRT6',
  );
}
