// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYAC6GkojZqCAxZOxzl2DQBvxzlh5PYk',
    appId: '1:38556368036:web:7e23362bb6df49d7a07a31',
    messagingSenderId: '38556368036',
    projectId: 'attend-e30da',
    authDomain: 'attend-e30da.firebaseapp.com',
    storageBucket: 'attend-e30da.firebasestorage.app',
    measurementId: 'G-QM2PS3W7QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMutynddfyIgrn0vdmLbkxYhsXZXyN6Ck',
    appId: '1:38556368036:android:fc6adbdd362374aaa07a31',
    messagingSenderId: '38556368036',
    projectId: 'attend-e30da',
    storageBucket: 'attend-e30da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGPaoeEkxkNiStlc2bJnMZmfWKaQWyegU',
    appId: '1:38556368036:ios:5bdae3089d7b05cca07a31',
    messagingSenderId: '38556368036',
    projectId: 'attend-e30da',
    storageBucket: 'attend-e30da.firebasestorage.app',
    iosBundleId: 'com.example.attend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGPaoeEkxkNiStlc2bJnMZmfWKaQWyegU',
    appId: '1:38556368036:ios:5bdae3089d7b05cca07a31',
    messagingSenderId: '38556368036',
    projectId: 'attend-e30da',
    storageBucket: 'attend-e30da.firebasestorage.app',
    iosBundleId: 'com.example.attend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwYAC6GkojZqCAxZOxzl2DQBvxzlh5PYk',
    appId: '1:38556368036:web:7b11c61da3771304a07a31',
    messagingSenderId: '38556368036',
    projectId: 'attend-e30da',
    authDomain: 'attend-e30da.firebaseapp.com',
    storageBucket: 'attend-e30da.firebasestorage.app',
    measurementId: 'G-9ZRJZ0NT3H',
  );
}
